// Auto-generated by scripts/optimize-images.mjs
export const blurDataURLs: Record<string, string> = {
  "accueil-hero": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoKAAMABUB8JZwAAwF73hoiAAD+wZiBJdV0xU6rJ9BtlRx0TygoAA==",
  "apropos-hero": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABwAwCdASoKABYAPzmEuVOvKKWoMAgB4CcJZwAASjjklfGnUQAA/tzWSSzFZV7uPcqtAYMRCaMjm8sBgSVWlClVINNwbBCtYCAAAA==",
  "apropos-joel-portrait": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAwAgCdASoKAAwABUB8JZACdAELZWdBKuKFAAD+W1lVHY/K/qAaW5c2hGP3q5a3nPm8Scv/oApadSZLFgAAAA==",
  "contact-hero": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACQAQCdASoKAAUABUB8JZQAApZCgQAA+p9EFQJuSuTDWdlLkjZ72P8PaLtw+lFX+NWEAA==",
  "formations-hero": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACQAQCdASoKAAcABUB8JZQAAu0pb3AA/jyOuKyWokB2kFJb451LaAAA",
  "galerie-aube": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoKAAcABUB8JaACdACv9AdcAAD8HP/sxm8HXxegxtF904LEUEXWC7qLxLqerEQV0gAAAA==",
  "galerie-dun-monde-a-lautre": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoKAAoABUB8JbACdADZSA3gAP7kNhGUP5qFbVyenirLaOqk6ZQsY/19nU9QmB1c61xZOvqB7sXICQAA",
  "galerie-emergence": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoKABAABUB8JbACdAELXao1EADMUKvby+KRvqCfFYDZeU9RIonNn2rigJaSkNxW5nynmBsPzfyBOumEWJc8AA==",
  "galerie-enseignement": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADwAQCdASoKAAoABUB8JZwAAudjDaSrJ8AA/uk7pPZ6Dm0rQfHJm7SgAAA=",
  "galerie-mediumnite": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoKAAgABUB8JZgCw7DbVFGeAAD+qgetsW3qZOupK/zjOzDDFTQAKRoAAAA=",
  "geobiologie-demarche": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoKAAcABUB8JYgCdAD8LjyAGYAA/kDv2+9fcRaOIq+ppmuS9eMWwBES+KfAWKWQRC14AA==",
  "geobiologie-hero": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAABwAQCdASoKAA0ABUB8JZQAApcdQAD44VRULeDAc85dCNLFQcbtVwNBZupRUMB4s/e8arYEAAA=",
  "geobiologie-histoire": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoKAA0ABUB8JbACdGuAAkNmAQAA/eOlFVYx91hOoKPJtrxjbspfaMdEF3gUcXiTcD9j0ORxQAAAAA==",
  "mediumnite-contact-defunt": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAABwAQCdASoKAAgABUB8JbACdAF1AAD+74OorZdoVtKI37STKiJHTAp4uOuyCGgAAAA=",
  "mediumnite-hero": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoKAAYABUB8JYwCdADZkL0AAP7CQ+iSrftkrHwwuaE+Y4wxLi4AAA==",
  "tarifs-hero": "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACQAQCdASoKAAUABUB8JZQAAtz2YqAA/ty9tbedr4bOTaWYAAA="
};
