import sharp from "sharp";
import { readdir, mkdir, rename, writeFile } from "fs/promises";
import { join, parse } from "path";

const IMAGES_DIR = join(import.meta.dirname, "..", "public", "images");
const ORIGINALS_DIR = join(IMAGES_DIR, "originals");
const BLUR_OUTPUT = join(import.meta.dirname, "..", "src", "lib", "blur-data.ts");

// Hero images get max 1920px width, content images get max 1200px
const HERO_MAX_WIDTH = 1920;
const CONTENT_MAX_WIDTH = 1200;
const WEBP_QUALITY = 80;
const BLUR_WIDTH = 10;

const isHeroImage = (name) => name.includes("-hero") || name === "accueil-hero.jpg";

async function run() {
  // Create originals backup dir
  await mkdir(ORIGINALS_DIR, { recursive: true });

  const files = await readdir(IMAGES_DIR);
  const imageFiles = files.filter(
    (f) => /\.(jpg|jpeg|png)$/i.test(f) && f !== "logo.png"
  );

  console.log(`Found ${imageFiles.length} images to optimize\n`);

  const blurEntries = {};

  for (const file of imageFiles) {
    const inputPath = join(IMAGES_DIR, file);
    const { name } = parse(file);
    const outputPath = join(IMAGES_DIR, `${name}.webp`);
    const maxWidth = isHeroImage(file) ? HERO_MAX_WIDTH : CONTENT_MAX_WIDTH;

    // Convert to WebP (rotate() applies EXIF orientation to pixels)
    const info = await sharp(inputPath)
      .rotate()
      .resize({ width: maxWidth, withoutEnlargement: true })
      .webp({ quality: WEBP_QUALITY })
      .toFile(outputPath);

    // Generate LQIP blur placeholder
    const blurBuffer = await sharp(inputPath)
      .rotate()
      .resize(BLUR_WIDTH)
      .webp({ quality: 20 })
      .toBuffer();

    const blurDataURL = `data:image/webp;base64,${blurBuffer.toString("base64")}`;
    blurEntries[name] = blurDataURL;

    // Get original size for comparison
    const originalMeta = await sharp(inputPath).metadata();
    const originalSize = (await import("fs")).statSync(inputPath).size;
    const reduction = ((1 - info.size / originalSize) * 100).toFixed(1);

    console.log(
      `${file} -> ${name}.webp | ${(originalSize / 1024).toFixed(0)}KB -> ${(info.size / 1024).toFixed(0)}KB (-${reduction}%) | ${originalMeta.width}x${originalMeta.height} -> ${info.width}x${info.height}`
    );

    // Move original to backup
    await rename(inputPath, join(ORIGINALS_DIR, file));
  }

  // Write blur data TypeScript file
  const tsContent = `// Auto-generated by scripts/optimize-images.mjs
export const blurDataURLs: Record<string, string> = ${JSON.stringify(blurEntries, null, 2)};
`;
  await writeFile(BLUR_OUTPUT, tsContent, "utf-8");

  console.log(`\nBlur data written to src/lib/blur-data.ts (${Object.keys(blurEntries).length} entries)`);
  console.log("Originals moved to public/images/originals/");
}

run().catch(console.error);
